#!/usr/bin/env python3
"""
Generate the subagent fleet from scaffold/roster.py.

Emits (relative to repo root):
  - agents/<department>/<name>.md   one Claude-Code-style subagent per entry
  - SKILLS.md                        agent -> skills manifest + install commands
  - README.md                        fleet overview + usage

Re-run any time after editing roster.py:  python3 scaffold/generate.py
"""
import json
import os
import textwrap
from roster import ROSTER

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

DEPT_TITLES = {
    "engineering": "🛠 Engineering",
    "quality": "✅ Quality & Testing",
    "data-ai": "🗄 Data & AI",
    "infrastructure": "☁️ Infrastructure",
    "design": "🎨 Design",
    "product": "📋 Product & Research",
    "meta": "🧭 Meta / Orchestration",
}
DEPT_ORDER = list(DEPT_TITLES.keys())


def bullets(items):
    return "\n".join(f"- {x}" for x in items)


def numbered(items):
    return "\n".join(f"{i}. {x}" for i, x in enumerate(items, 1))


def skill_lines(skills):
    return "\n".join(f"- `{sid}` — {note}" for sid, note in skills)


# External frameworks that ship their own installer (not skills.sh packages).
FRAMEWORK_SKILLS = {"gsd"}


def local_skill_slugs():
    """Skills authored in this repo under skills/<slug>/SKILL.md."""
    skills_dir = os.path.join(ROOT, "skills")
    if not os.path.isdir(skills_dir):
        return set()
    return {
        d for d in os.listdir(skills_dir)
        if os.path.isfile(os.path.join(skills_dir, d, "SKILL.md"))
    }


def classify(sid, local):
    """registry (skills.sh) | local (repo-authored) | framework | bundled (harness)."""
    if "/" in sid:
        return "registry"
    if sid in FRAMEWORK_SKILLS:
        return "framework"
    if sid in local:
        return "local"
    return "bundled"


def build_agents_index():
    return [
        {
            "name": a["name"],
            "department": a["department"],
            "title": a["title"],
            "description": a["description"],
            "model": a["model"],
            "tools": a["tools"],
            "skills": [sid for sid, _ in a["skills"]],
            "handoffs": a["handoffs"],
        }
        for a in ROSTER
    ]


def build_skills_index(local):
    idx = {}
    for a in ROSTER:
        for sid, note in a["skills"]:
            e = idx.setdefault(sid, {
                "kind": classify(sid, local),
                "note": note,
                "used_by": [],
                "departments": [],
            })
            e["used_by"].append(a["name"])
            if a["department"] not in e["departments"]:
                e["departments"].append(a["department"])
    return idx


def write_meta_skills():
    """Generate the discovery skills (find-subagents, select-skills) from the roster.

    These are local skills; writing them here keeps their embedded roster/catalog in
    sync with roster.py on every generate, and install.sh distributes them like any
    other local skill.
    """
    gen_note = "> Auto-generated by `scaffold/generate.py` from `scaffold/roster.py`. Do not edit by hand."

    # ---- find-subagents (team directory) ----
    d = os.path.join(ROOT, "skills", "find-subagents")
    os.makedirs(d, exist_ok=True)
    fs = [
        "---",
        "name: find-subagents",
        "description: Use to discover the available specialist subagents and route a task "
        "to the right one. Lists every agent by department with when-to-use guidance; read "
        "the adjacent agents.json for the machine-readable roster (name, description, skills, handoffs).",
        "---",
        "",
        "# Find Subagents (Team Directory)",
        "",
        gen_note,
        "",
        'Use this to answer "who on the team should do this task?" Match the task to the',
        "agent whose **use-when** description fits best, then delegate to that subagent —",
        "or, if you are the `dynamic-agent`, adopt that persona and its standards.",
        "",
        "## Routing procedure",
        "1. Restate the task and its definition of done.",
        "2. Scan the department matching the task's domain (below).",
        "3. Pick the **most specific** specialist whose description fits. For work spanning",
        "   multiple departments, route through `company-orchestrator`; within engineering,",
        "   through `tech-lead`.",
        "4. For the exact skills that agent should load, use the `select-skills` skill.",
        "5. Full machine-readable roster: read `agents.json` in this skill's folder.",
        "",
        "## Roster",
        "",
    ]
    for dept in DEPT_ORDER:
        ags = [a for a in ROSTER if a["department"] == dept]
        if not ags:
            continue
        fs.append(f"### {DEPT_TITLES[dept]}")
        fs.append("")
        for a in ags:
            fs.append(f"- **`{a['name']}`** — {a['description']}")
        fs.append("")
    with open(os.path.join(d, "SKILL.md"), "w") as f:
        f.write("\n".join(fs))

    # ---- select-skills (skill router) ----
    d2 = os.path.join(ROOT, "skills", "select-skills")
    os.makedirs(d2, exist_ok=True)
    ss = [
        "---",
        "name: select-skills",
        "description: Use before starting a task to choose the proper skills to load for it. "
        "Lists the skills relevant to each domain/department; read the adjacent skills.json for "
        "the full catalog (id, kind, what it's for, which agents use it).",
        "---",
        "",
        "# Select Skills (Skill Router)",
        "",
        gen_note,
        "",
        'Use this to answer "which skills should I load for this task?" Loading the right',
        "2–5 skills sharpens the work; loading everything wastes context.",
        "",
        "## Selection procedure",
        "1. Classify the task's domain(s): frontend, backend, mobile, testing, data, infra,",
        "   design, product/research, security, orchestration.",
        "2. From the matching domain(s) below, pick the 2–5 skills that fit the task.",
        "3. Load them with the `Skill` tool. If a skill isn't installed, install it per the",
        "   repo `SKILLS.md` (registry via `npx skills add`, local via `install.sh`, GSD via",
        "   `install-gsd.sh`).",
        "4. Prefer skills already listed for your role; add cross-domain skills only as needed.",
        "5. Full machine-readable catalog: read `skills.json` in this skill's folder.",
        "",
        "## Skills by domain (department)",
        "",
    ]
    for dept in DEPT_ORDER:
        seen = {}
        for a in ROSTER:
            if a["department"] != dept:
                continue
            for sid, note in a["skills"]:
                seen.setdefault(sid, note)
        if not seen:
            continue
        ss.append(f"### {DEPT_TITLES[dept]}")
        ss.append("")
        for sid in sorted(seen):
            ss.append(f"- `{sid}` — {seen[sid]}")
        ss.append("")
    with open(os.path.join(d2, "SKILL.md"), "w") as f:
        f.write("\n".join(ss))

    # JSON indexes (written after SKILL.md exist so classify() sees them as local)
    local = local_skill_slugs()
    with open(os.path.join(d, "agents.json"), "w") as f:
        json.dump(build_agents_index(), f, indent=2)
    with open(os.path.join(d2, "skills.json"), "w") as f:
        json.dump(build_skills_index(local), f, indent=2)


def render_agent(a):
    skill_ids = [sid for sid, _ in a["skills"]]
    fm = [
        "---",
        f"name: {a['name']}",
        f'description: "{a["description"]}"',
        f"tools: {a['tools']}",
        f"model: {a['model']}",
        f"department: {a['department']}",
        "skills:",
    ]
    fm += [f"  - {sid}" for sid in skill_ids]
    fm.append("---")
    frontmatter = "\n".join(fm)

    body = f"""
You are a **{a['title']}** operating as part of a full cross-functional tech company built from specialised subagents. You own your domain deeply and collaborate through clean handoffs with the rest of the org.

## Skills
Before doing substantive work, load and follow the skills below (via the `Skill` tool where the skill is available in this harness; otherwise install per `SKILLS.md`). They encode the current best practices for your role:

{skill_lines(a['skills'])}

## Expertise
{bullets(a['expertise'])}

## When invoked
{numbered(a['when'])}

## Standards
{bullets(a['standards'])}

## Collaboration
Hand off to or pull in these teammates when the work crosses your boundary:
{bullets(f"`{h}`" for h in a['handoffs'])}

## Communication protocol
- Begin by restating the goal, constraints, and definition of done in one or two lines.
- State assumptions explicitly; ask only when a decision is genuinely the caller's to make.
- Report outcomes faithfully: what changed, what was verified (and how), and what is still open.
- When you reach the edge of your specialism, name the teammate who should take it and summarise the context they need.
"""
    return frontmatter + "\n" + body.rstrip() + "\n"


def write_agents():
    count = 0
    for a in ROSTER:
        d = os.path.join(ROOT, "agents", a["department"])
        os.makedirs(d, exist_ok=True)
        path = os.path.join(d, f"{a['name']}.md")
        with open(path, "w") as f:
            f.write(render_agent(a))
        count += 1
    return count


def write_skills_manifest():
    local = local_skill_slugs()
    lines = [
        "# Skills Manifest",
        "",
        "Every subagent references a set of **skills** — reusable packages of procedural",
        "best-practice knowledge. Subagents don't install skills; they *use* them (via the",
        "`Skill` tool). This file is the source of truth for which skills each agent expects",
        "and how each kind is installed and kept up to date.",
        "",
        "## Skill kinds",
        "",
        "| Kind | Looks like | Installed by |",
        "|---|---|---|",
        "| **registry** | `owner/repo` | `npx skills add owner/repo` (skills.sh) |",
        "| **local** | single word, authored in `skills/<slug>/` | `bash install.sh` copies it into each harness |",
        "| **framework** | `gsd` | its own installer — see below |",
        "| **bundled** | single word (e.g. `jira-ticket-planner`, `drawio`, `dataviz`) | already provided by the harness — no install |",
        "",
        "## Install & update (one command each)",
        "",
        "```bash",
        "bash scaffold/install-skills.sh   # install every registry skill the fleet uses",
        "bash scaffold/update-skills.sh    # update ALL installed registry skills to latest",
        "bash scaffold/install-gsd.sh      # install the GSD workflow framework",
        "bash install.sh                   # (re)install agents + local skills into harnesses",
        "```",
        "",
        "`update-skills.sh` runs `npx skills update`, which the skills.sh CLI uses to pull the",
        "latest version of every installed skill across all your harnesses from one place.",
        "Re-run `install.sh` after editing a local skill (e.g. `tailwind`) to redistribute it.",
        "",
        "## Skills by agent",
        "",
    ]

    kinds = {"registry": set(), "local": set(), "framework": set(), "bundled": set()}

    for dept in DEPT_ORDER:
        agents = [a for a in ROSTER if a["department"] == dept]
        if not agents:
            continue
        lines.append(f"### {DEPT_TITLES[dept]}")
        lines.append("")
        lines.append("| Agent | Skills |")
        lines.append("|---|---|")
        for a in agents:
            sk = []
            for sid, _ in a["skills"]:
                sk.append(f"`{sid}`")
                kinds[classify(sid, local)].add(sid)
            lines.append(f"| `{a['name']}` | {', '.join(sk)} |")
        lines.append("")

    lines.append("## Registry skills — install commands (deduplicated)")
    lines.append("")
    lines.append("```bash")
    for sid in sorted(kinds["registry"]):
        lines.append(f"npx skills add {sid}")
    lines.append("```")
    lines.append("")
    lines.append("## Local skills (authored in this repo, distributed by `install.sh`)")
    lines.append("")
    for sid in sorted(kinds["local"]):
        lines.append(f"- `{sid}` — `skills/{sid}/SKILL.md`")
    lines.append("")
    lines.append("## Framework skills (own installer)")
    lines.append("")
    for sid in sorted(kinds["framework"]):
        lines.append(f"- `{sid}` — the [GSD](https://github.com/shoootyou/get-shit-done-multi) "
                     "spec-driven workflow. Install with `bash scaffold/install-gsd.sh`.")
    lines.append("")
    lines.append("## Bundled skills (provided by the harness — no install)")
    lines.append("")
    for sid in sorted(kinds["bundled"]):
        lines.append(f"- `{sid}`")
    lines.append("")
    lines.append(
        f"> Totals: {len(kinds['registry'])} registry + {len(kinds['local'])} local + "
        f"{len(kinds['framework'])} framework + {len(kinds['bundled'])} bundled skills "
        f"across {len(ROSTER)} agents."
    )
    lines.append("")

    with open(os.path.join(ROOT, "SKILLS.md"), "w") as f:
        f.write("\n".join(lines))
    return kinds


def write_readme(kinds):
    counts = {}
    for a in ROSTER:
        counts[a["department"]] = counts.get(a["department"], 0) + 1

    lines = [
        "# Tech Company Subagent Fleet",
        "",
        f"A cross-functional **tech company built from {len(ROSTER)} specialised subagents** —",
        "engineering, quality, data, infrastructure, design, and product — each paired with the",
        "real, installable **skills** it needs. Inspired by",
        "[VoltAgent/awesome-claude-code-subagents](https://github.com/VoltAgent/awesome-claude-code-subagents)",
        "and the [skills.sh](https://www.skills.sh) ecosystem.",
        "",
        "## Departments",
        "",
    ]
    for dept in DEPT_ORDER:
        agents = [a for a in ROSTER if a["department"] == dept]
        if not agents:
            continue
        lines.append(f"### {DEPT_TITLES[dept]} ({len(agents)})")
        lines.append("")
        for a in agents:
            lines.append(f"- **`{a['name']}`** — {a['description']}")
        lines.append("")

    lines += [
        "## Layout",
        "",
        "```",
        "agents/",
        *[f"  {d}/    # {DEPT_TITLES[d]} ({counts.get(d,0)})" for d in DEPT_ORDER],
        "skills/                # locally-authored skills (e.g. tailwind/SKILL.md)",
        "SKILLS.md              # which skills each agent uses + install/update commands",
        "install.sh             # install agents (+ local skills) into all four harnesses",
        "scaffold/",
        "  roster.py            # single source of truth for the fleet",
        "  generate.py          # regenerates agents/, SKILLS.md, README.md",
        "  install-skills.sh    # installs all skills.sh registry skills the fleet uses",
        "  update-skills.sh     # updates ALL installed registry skills to latest (one cmd)",
        "  install-gsd.sh       # installs the GSD spec-driven workflow framework",
        "```",
        "",
        "## Install the agents",
        "",
        "The installer targets four harnesses and converts formats as needed:",
        "",
        "| Harness | Destination | Format |",
        "|---|---|---|",
        "| Claude Code | `~/.claude/agents/<dept>/` | Markdown + frontmatter (native subagents) |",
        "| opencode | `~/.config/opencode/agent/` | Markdown + frontmatter |",
        "| Codex | `~/.codex/agents/` | TOML (auto-converted) |",
        "| pi | `~/.pi/agent/prompts/` | Markdown prompt templates |",
        "",
        "```bash",
        "# install into every detected harness (global)",
        "bash install.sh",
        "",
        "# or target specific harnesses",
        "bash install.sh --claude --opencode",
        "bash install.sh --codex",
        "bash install.sh --pi",
        "",
        "# install into the current project instead of the home dir",
        "bash install.sh --claude --project",
        "",
        "# preview without writing anything",
        "bash install.sh --all --dry-run",
        "```",
        "",
        "## Install & update the skills",
        "",
        "See [`SKILLS.md`](./SKILLS.md) for the full agent→skill mapping and the four skill",
        "kinds (registry / local / framework / bundled).",
        "",
        "```bash",
        "bash scaffold/install-skills.sh   # install every skills.sh registry skill",
        "bash scaffold/update-skills.sh    # update ALL installed skills to latest (one command)",
        "bash scaffold/install-gsd.sh      # install the GSD workflow framework",
        "```",
        "",
        "`update-skills.sh` wraps `npx skills update` — the skills.sh CLI keeps every installed",
        "skill in sync with its upstream source across all harnesses from a single command.",
        "",
        f"Referenced across the fleet: **{len(kinds['registry'])} registry**, "
        f"**{len(kinds['local'])} local**, **{len(kinds['framework'])} framework**, and "
        f"**{len(kinds['bundled'])} bundled** skills.",
        "",
        "### Web styling: Tailwind + shadcn/ui",
        "",
        "Web agents (`nextjs-dev`, `reactjs-dev`, `fullstack-dev`, `design-system-engineer`)",
        "carry the `tailwind` local skill plus `google-labs-code/shadcn-ui`; `react-native-dev`",
        "uses `expo/expo-tailwind-setup` (NativeWind). Edit `skills/tailwind/SKILL.md` to change",
        "your Tailwind conventions, then re-run `bash install.sh`.",
        "",
        "### Workflow framework: GSD (not Superpowers)",
        "",
        "This fleet standardises on **[GSD (Get Shit Done)](https://github.com/shoootyou/get-shit-done-multi)**",
        "— a spec-driven *plan → execute → verify* workflow — as its orchestration layer, rather",
        "than the Superpowers (obra/*) TDD skills, to avoid two competing workflow philosophies.",
        "`company-orchestrator`, `tech-lead`, and `product-owner` drive work through GSD; language",
        "and testing skills (testmu, trailofbits, etc.) remain as techniques on top of it.",
        "",
        "## Discovery & dynamic delegation",
        "",
        "Three pieces let the fleet route work and load skills on the fly:",
        "",
        "- **`find-subagents`** (local skill) — a generated team directory: every agent by",
        "  department with when-to-use guidance, plus a machine-readable `agents.json`. Any",
        "  agent (or you) can invoke it to answer *\"who should do this task?\"*",
        "- **`select-skills`** (local skill) — a generated skill router: the skills relevant to",
        "  each domain, plus a machine-readable `skills.json` (id, kind, what-for, used-by). Answers",
        "  *\"which skills should I load for this task?\"* so agents use the **proper** skills per task.",
        "- **`dynamic-agent`** — a generalist with no fixed specialism. Give it a delegated task;",
        "  it uses `find-subagents` to adopt the right persona, `select-skills` to load the matching",
        "  skills dynamically, executes, and escalates to a fixed specialist when depth is needed.",
        "",
        "Both skills are regenerated from the roster on every `generate.py` run, so the directory",
        "and catalog never drift from the actual agents.",
        "",
        "## Customise / extend",
        "",
        "`scaffold/roster.py` is the single source of truth. Add or edit an agent there, then:",
        "",
        "```bash",
        "python3 scaffold/generate.py   # regenerates agents/, SKILLS.md, README.md",
        "```",
        "",
        "Then re-run `install.sh` to push the changes to your harnesses.",
        "",
        "## How subagents and skills fit together",
        "",
        "- A **subagent** is a role: a persona, a tool scope, and a working protocol.",
        "- A **skill** is portable know-how the agent loads on demand.",
        "- The orchestrators (`company-orchestrator`, `tech-lead`) decompose an initiative and",
        "  route each piece to the right specialist, who pulls in its skills to do the work.",
        "",
    ]
    with open(os.path.join(ROOT, "README.md"), "w") as f:
        f.write("\n".join(lines))


def main():
    n = write_agents()
    write_meta_skills()   # generate find-subagents + select-skills before classifying
    kinds = write_skills_manifest()
    write_readme(kinds)
    print(f"Generated {n} agents across {len(DEPT_ORDER)} departments.")
    print(f"SKILLS.md: {len(kinds['registry'])} registry + {len(kinds['local'])} local + "
          f"{len(kinds['framework'])} framework + {len(kinds['bundled'])} bundled skills.")
    print("Wrote README.md.")


if __name__ == "__main__":
    main()
